### ISSUE TITLE
Create jobs resource

### ISSUE THREAD

**Issue by edwardleoni** [pixelfusion/cavalry-api#4]
https://paper.dropbox.com/doc/Cavalry-API-Potential-Endpoints-C8lgIKCzCVvwTaiGCrgwW

1. - [ ] POST /jobs/start
2. - [ ] POST /jobs/xxx/get-destination
3. - [ ] GET /jobs/xxxx
4. - [ ] PATCH /jobs/xxxx
5. - [ ] POST /jobs/xxxx/messages
6. - [ ] GET /jobs/xxxx/messages
7. - [ ] GET /jobs/xxxx

**Job statuses**
- started - A job that has already started
- uploading - A job that is perfoming upload to destination
- failed - A job that has started but failed to finished
- completed - A job that has finished its execution

**Comment by titopixelfusion** [comment]
3. and 7. seem to be the same endpoint
